name: Update Homebrew Formula
description: This action updates homebrew formula used to install kelper

inputs:
  release_tag:
    description: "release tag"
    required: true
  amd64_artifact_path:
    description: "Path to the downloaded x86_64 macOS binary artifact"
    required: true
  arm64_artifact_path:
    description: "Path to the downloaded aarch64 macOS binary artifact"
    required: true
  amd64_artifact_name:
    description: "amd64 artifact build name"
    required: true
    default: "kelper-x86_64-apple-darwin"
  arm64_artifact_name:
    description: "arm64 artifact build name"
    required: true
    default: "kelper-aarch64-apple-darwin"
  tap_repo:
    description: "The owner/repo name of the tap repository (e.g., your-username/homebrew-your-tap-name)"
    required: true
  formula_path:
    description: "Path to the formula file within the tap repository (e.g., Formula/kelper.rb)"
    required: true
    default: "Formula/kelper.rb"
  repository:
    description: "Repository name for the formula"
    required: true
  tap_token:
    description: "GitHub token (PAT) with write access to the tap repository"
    required: true

runs:
  using: "composite"
  steps:
    - name: Calculate SHA256 for macOS binaries
      id: shas
      run: |
        AMD64_SHA=$(sha256sum "${{ inputs.amd64_artifact_path }}" | awk '{ print $1 }')
        ARM64_SHA=$(sha256sum "${{ inputs.arm64_artifact_path }}" | awk '{ print $1 }')
        echo "amd64_sha256=$AMD64_SHA" >> $GITHUB_OUTPUT
        echo "arm64_sha256=$ARM64_SHA" >> $GITHUB_OUTPUT
        echo "Calculated SHA256 (amd64): $AMD64_SHA for path: ${{ inputs.amd64_artifact_path }}"
        echo "Calculated SHA256 (arm64): $ARM64_SHA for path: ${{ inputs.arm64_artifact_path }}"
      shell: bash

    - name: Update Homebrew Formula Script
      id: update_script
      run: |
        chmod +x ./update-homebrew-formula.sh
        ./update-homebrew-formula.sh \\
          "${{ inputs.tap_repo }}" \\
          "${{ inputs.formula_path }}" \\
          "${{ inputs.release_tag }}" \\
          "${{ inputs.repository }}" \\
          "${{ steps.shas.outputs.amd64_sha256 }}" \\
          "${{ steps.shas.outputs.arm64_sha256 }}" \\
          "${{ inputs.amd64_artifact_name }}" \\
          "${{ inputs.arm64_artifact_name }}" \\
          "Brew formula update for version ${{ inputs.release_tag }}" \\
          "${{ inputs.tap_token }}"
      shell: bash
      env:
        # Pass the secret to the environment for git operations within the script
        GITHUB_TOKEN: ${{ inputs.tap_token }}
