apiVersion: krew.googlecontainertools.github.io/v1alpha2
kind: Plugin
metadata:
  name: kelper
spec:
  version: {{ .TagName }}
  shortDescription: A CLI tool to serve as swiss-army knife for your operations on Kubernetes pods and nodes
  description: |
    Kelper helps manage your kubernetes resources efficiently by performing multiple commands
    on nodes and pods. It consists of all the ideal utilities that should have been a part of kubectl
  homepage: https://github.com/aliabbasjaffri/kelper
  platforms:
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      {{addURIAndSha "https://github.com/aliabbasjaffri/kelper/releases/download/{{ .TagName }}/kelper-{{ .TagName }}-x86_64-unknown-linux-musl" .TagName | indent 6 }}
      bin: kelper
    - selector:
        matchLabels:
          os: linux
          arch: arm64
      {{addURIAndSha "https://github.com/aliabbasjaffri/kelper/releases/download/{{ .TagName }}/kelper-{{ .TagName }}-aarch64-unknown-linux-musl" .TagName | indent 6 }}
      bin: kelper
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      {{addURIAndSha "https://github.com/aliabbasjaffri/kelper/releases/download/{{ .TagName }}/kelper-{{ .TagName }}-x86_64-apple-darwin" .TagName | indent 6 }}
      bin: kelper
    - selector:
        matchLabels:
          os: darwin
          arch: arm64
      {{addURIAndSha "https://github.com/aliabbasjaffri/kelper/releases/download/{{ .TagName }}/kelper-{{ .TagName }}-aarch64-apple-darwin" .TagName | indent 6 }}
      bin: kelper
    - selector:
        matchLabels:
          os: windows
          arch: amd64
      {{addURIAndSha "https://github.com/aliabbasjaffri/kelper/releases/download/{{ .TagName }}/kelper-{{ .TagName }}-x86_64-pc-windows-msvc.exe" .TagName | indent 6 }}
      bin: kelper.exe
